### ISSUE TITLE
ETP-445: Sub-applications in Etendo Mobile crash when cached on Android devices

### ISSUE THREAD

**Issue by juanfunes1996** [etendosoftware/etendo_mobile#14]
# Error's description

Sub-applications in Etendo Mobile crash when cached on Android devices

# Steps to reproduce the error

- Open the Etendo Mobile application on an Android device.
- Access any sub-application within Etendo.
- Minimize the application or switch to another application, allowing the Etendo sub-application to be cached.
- After some time, reopen the Etendo Mobile application and try to access the cached sub-application.

# Expected behavior

The sub-application should resume smoothly from its cached state and allow further interactions.

# Affected Version 

Mobile: 1.7.1

# Other test cases

  Given:

  When:

  Then:

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [1.8.0](https://github.com/etendosoftware/etendo_mobile/releases/tag/1.8.0) ⚡ 🚀

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [1.8.1](https://github.com/etendosoftware/etendo_mobile/releases/tag/1.8.1) ⚡ 🚀
